### PR TITLE
help umsgpack find message boundaries

### LINKED ISSUE #7: Can't launch corecount.py correctly
I managed to synthesize corescore for colorlight_5a75b. Seems to works but if I open terminal on uart I have an end of line problem :
```shell
$ screen /dev/ttyUSB0 57600
  �Core 00002 says hello
                        �Core 00003 says hello
                                              �Core 00004 says hello
                                                                    �Core 00006 says hello
                                                                                          �Core 00007 says hello
```

I tried to use corecount.py script instead of standard uart terminal but I have an exception on msgpack:

```shell

$ python ./fusesoc_libraries/corescore/sw/corecount.py /dev/ttyUSB0
Traceback (most recent call last):
  File "./fusesoc_libraries/corescore/sw/corecount.py", line 50, in <module>
    curses.wrapper(main)
  File "/usr/local/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "./fusesoc_libraries/corescore/sw/corecount.py", line 39, in main
    u = umsgpack.unpack(ser)
  File "/home/user/pyenv/envp37/lib/python3.7/site-packages/msgpack/__init__.py", line 58, in unpack
    return unpackb(data, **kwargs)
  File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
msgpack.exceptions.UnpackValueError: Unpack failed: error = 0
```

My python version is : 
```shell
$ python --version
Python 3.7.4
```

### PR DESCRIPTION
**Pull request by bluecmd**
Sometimes umsgpack seems to get confused when the bytestream
is not correctly aligned.

Fixes #7

### CODE REVIEW

**Comment by olofk** [comment]
I'm a bit confused. Do you need both msgpack and umsgpack for this? Can we find a way to only rely on one of them?

**Comment by bluecmd** [comment]
Ah, maybe that's because I kept running with `MSGPACK_PUREPYTHON=1` to get the error message. Let me try a bit without that option.

EDIT: No, even without that the following happens:
```
[riki]$ python3 sw/corecount.py /dev/ttyS6
Traceback (most recent call last):
  File "sw/corecount.py", line 53, in <module>
    curses.wrapper(main)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "sw/corecount.py", line 42, in main
    u = umsgpack.unpackb(d)
  File "/home/bluecmd/.local/lib/python3.6/site-packages/umsgpack.py", line 19, in unpackb
    return msgpack.unpackb(buf, **kwargs)
  File "msgpack/_unpacker.pyx", line 208, in msgpack._unpacker.unpackb
msgpack.exceptions.ExtraData: unpack(b) received extra data.
```

As you can see umsgpack raises an exception that is defined in msgpack. So either we have to catch all exceptions, or import msgpack to refer to this one specifically as I see it. Unless we know specifically what to do to not feed it invalid data in the first place, but that's beyond my knowledge.

**Comment by olofk** [comment]
So I decided to take #17 and now this commit conflicts. I still think it would be great to have this as well, since there are still problems with message boundraries. Do you want to rebase it on top of the current HEAD?

**Comment by bluecmd** [comment]
I can probably do this some time in the future, I am right now moving house and all my FPGA stuff is packed down so I don't think I can test this fully if I were to remake the change for msgpack.

**Comment by olofk** [comment]
Ah cool. I'll see if I can easily rebase it here or just reimplement it otherwise. Good luck with the move

**Pull request closed without merging**
