### PR TITLE
Reformat Python code to pep8 and .core to YAML standards

### PR DESCRIPTION
**Pull request by carlosedp**

### CODE REVIEW

**Comment by olofk** [comment]
Hmm... this lokoks mostly good but for some reason it also tries to format the inline RISC-V assembly code and replaces `#define` with `# define` which probably won't work

**Comment by carlosedp** [comment]
Oh, that's pretty bad... sorry I didn't catch it up.
Will look on how it can ignore that.

**Comment by carlosedp** [comment]
Better now :)

**Comment by olofk** [comment]
Perfect! Thanks

**Pull request merged**
