### PR TITLE
Ep2c5t144 devboard

### PR DESCRIPTION
**Pull request by tomverbeure**
Corescore for that good old EP2C5T144 devboard.

Needs Quartus 13.0sp1 (or something earlier) to compile...

image

### CODE REVIEW

**Comment by tomverbeure** [comment]
Note: this submission was created with a patched emitter.v to work around issue #31.

**Comment by olofk** [comment]
Sorry. Completely missed this PR. Are we all good now with the version bump of servant to fix the missing reset signal?

**Comment by tomverbeure** [comment]
We're good!

**Comment by olofk** [comment]
That was all I needed to hear. Thank you for tje contribution and let's hope the next one is less painful :)

**Pull request merged**
